version: 2
updates:
  # Keep Python dependencies up to date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore patch updates for non-critical packages
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: "pip"
      include: "scope"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy"
        update-types:
          - "minor"
          - "patch"

  # Keep Docker dependencies up to date
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"

  # Keep Docker Compose dependencies up to date
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker-compose"
    target-branch: "main"
    commit-message:
      prefix: "docker-compose"
      include: "scope"
    reviewers:
      - "monoti"
